name: medical
dependencies:
- python=3.7
- pandas=1.0.4
- numpy=1.18.5
- matplotlib=3.2.1
- simpleitk=1.2.4
- pywavelets=1.0.0
- r-base=4.0.0
- r-mass=7.3_51.6
- r-tidyverse=1.3.0
- r-ggcorrplot=0.1.3
- r-dbscan=1.1_5
- r-factoextra=1.0.7
- pip:
  - pyradiomics==3.0
